name: Build and test Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v6
      - name: Install and check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v3
        with:
          packages: greenbone
          linter: ruff check
          python-version: ${{ matrix.python-version }}

  unittest:
    name: Unit-Tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v6
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run python -m unittest -v -b

  integrationtest:
    name: Integration-Tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - uses: actions/checkout@v6
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run python -m unittest -b -v
        env:
          RUN_INTEGRATION_TESTS: "true"

  coverage:
    name: Test Coverage
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/coverage-python@v3
        with:
          python-version: "3.13"
          token: ${{ secrets.CODECOV_TOKEN }}
          test-command: -m unittest -b
        env:
          RUN_ALL_TESTS: "true"

  mypy:
    name: Check Types
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v6
      - name: Run mypy
        uses: greenbone/actions/mypy-python@v3
        with:
          python-version: ${{ matrix.python-version }}
