name: Build and test Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - name: Install and check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v3
        with:
          packages: greenbone
          linter: ruff check
          python-version: "3.13"

  unittest:
    name: Unit-Tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v6
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run coverage run --data-file coverage.unit -m unittest -v -b
      - name: Upload coverage data
        if: matrix.python-version == '3.13'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-unit
          path: coverage.unit
          if-no-files-found: error

  integrationtest:
    name: Integration-Tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.13"
    steps:
      - uses: actions/checkout@v6
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: poetry run coverage run --data-file coverage.integration -m unittest -b -v
        env:
          RUN_INTEGRATION_TESTS: "true"
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-integration
          path: coverage.integration
          if-no-files-found: error

  coverage:
    name: Test Coverage
    runs-on: "ubuntu-latest"
    needs:
      - unittest
      - integrationtest
    steps:
      - uses: actions/checkout@v6
      - name: Download unit test coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-unit
      - name: Download integration test coverage data
        uses: actions/download-artifact@v4
        with:
          name: coverage-integration
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v3
        with:
          python-version: "3.13"
      - name: Combine coverage data
        run: |
          poetry run coverage combine coverage.unit coverage.integration
          poetry run coverage xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true

  mypy:
    name: Check Types
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
          - "3.13"
    steps:
      - uses: actions/checkout@v6
      - name: Run mypy
        uses: greenbone/actions/mypy-python@v3
        with:
          python-version: ${{ matrix.python-version }}
